# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: evaluator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'evaluator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65valuator.proto\"G\n\x0f\x45valuateRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x13\n\x0buser_answer\x18\x02 \x01(\t\x12\r\n\x05marks\x18\x03 \x01(\x05\"G\n\x10\x45valuateResponse\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x12\n\ntime_taken\x18\x02 \x01(\x02\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x03 \x01(\t2<\n\tEvaluator\x12/\n\x08\x45valuate\x12\x10.EvaluateRequest\x1a\x11.EvaluateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'evaluator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVALUATEREQUEST']._serialized_start=19
  _globals['_EVALUATEREQUEST']._serialized_end=90
  _globals['_EVALUATERESPONSE']._serialized_start=92
  _globals['_EVALUATERESPONSE']._serialized_end=163
  _globals['_EVALUATOR']._serialized_start=165
  _globals['_EVALUATOR']._serialized_end=225
# @@protoc_insertion_point(module_scope)
